[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "josh"
version = "0.0"

[tool.setuptools]
packages = ["josh"]
[tool.yapf]
based_on_style = "google"
indent_width = 4
column_limit = 160